<a href="https://colab.research.google.com/github/meinalisaa/pem-mesin/blob/main/Tugas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tugas 2 Lab PM
List Comprehension

In [ ]:
# cara membuat list manual 
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] 
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [ ]:
# menggunakan perulangan for
list2 = []
for x in range(1,16):
    list2.append(x)
print(list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [ ]:
# menggunakan list comprehension 
list3 = [x for x in range(1,16)] 
print(list3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Dictionary value to List

In [ ]:
def dictToList(dictionA):
    listA = [dictionA[key] for key in dictionA] 
    return listA

# pemanggilan fungsi
diction = {"key1":"value1", "key2":"value2", "key3":"value3"} 
print(dictToList(diction))

['value1', 'value2', 'value3']

Array 2D

In [ ]:
import numpy as np
arrA = np.array([2, -5, -11, 0, -9, 4, 6, 13, 4, 7, 12, -2]).reshape(3, 4)
print(arrA)

print('banyak entry = ', arrA.size)
print('dimensi array = ', arrA.ndim)
print('ukuran array = ', arrA.shape)

print(arrA[0:2, 1:4])
print(arrA[1:4, 0:3])

[[  2  -5 -11   0]
 [ -9   4   6  13]
 [  4   7  12  -2]]
banyak entry =  12
dimensi array =  2
ukuran array =  (3, 4)
[[ -5 -11   0]
 [  4   6  13]]
[[-9  4  6]
 [ 4  7 12]]

Data frame

In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/achmatim/data-mining/main/Dataset/iris.csv'
dfA = pd.read_csv(url)

dfA

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm           Label
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# data numerik
dfA.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [ ]:
# data non-numerik
dfA.describe(include=["object", "bool"])

              Label
count           150
unique            3
top     Iris-setosa
freq             50

In [ ]:
# pilih data yang label iris-setosa 
dfA[dfA['Label']=='Iris-setosa']

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm        Label
0             5.1           3.5            1.4           0.2  Iris-setosa
1             4.9           3.0            1.4           0.2  Iris-setosa
2             4.7           3.2            1.3           0.2  Iris-setosa
3             4.6           3.1            1.5           0.2  Iris-setosa
4             5.0           3.6            1.4           0.2  Iris-setosa
5             5.4           3.9            1.7           0.4  Iris-setosa
6             4.6           3.4            1.4           0.3  Iris-setosa
7             5.0           3.4            1.5           0.2  Iris-setosa
8             4.4           2.9            1.4           0.2  Iris-setosa
9             4.9           3.1            1.5           0.1  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
11            4.8           3.4            1.6           0.2  Iris-setosa
12            4.8           3.0            1.4           0.1  Iris-setosa
13            4.3           3.0            1.1           0.1  Iris-setosa
14            5.8           4.0            1.2           0.2  Iris-setosa
15            5.7           4.4            1.5           0.4  Iris-setosa
16            5.4           3.9            1.3           0.4  Iris-setosa
17            5.1           3.5            1.4           0.3  Iris-setosa
18            5.7           3.8            1.7           0.3  Iris-setosa
19            5.1           3.8            1.5           0.3  Iris-setosa
20            5.4           3.4            1.7           0.2  Iris-setosa
21            5.1           3.7            1.5           0.4  Iris-setosa
22            4.6           3.6            1.0           0.2  Iris-setosa
23            5.1           3.3            1.7           0.5  Iris-setosa
24            4.8           3.4            1.9           0.2  Iris-setosa
25            5.0           3.0            1.6           0.2  Iris-setosa
26            5.0           3.4            1.6           0.4  Iris-setosa
27            5.2           3.5            1.5           0.2  Iris-setosa
28            5.2           3.4            1.4           0.2  Iris-setosa
29            4.7           3.2            1.6           0.2  Iris-setosa
30            4.8           3.1            1.6           0.2  Iris-setosa
31            5.4           3.4            1.5           0.4  Iris-setosa
32            5.2           4.1            1.5           0.1  Iris-setosa
33            5.5           4.2            1.4           0.2  Iris-setosa
34            4.9           3.1            1.5           0.1  Iris-setosa
35            5.0           3.2            1.2           0.2  Iris-setosa
36            5.5           3.5            1.3           0.2  Iris-setosa
37            4.9           3.1            1.5           0.1  Iris-setosa
38            4.4           3.0            1.3           0.2  Iris-setosa
39            5.1           3.4            1.5           0.2  Iris-setosa
40            5.0           3.5            1.3           0.3  Iris-setosa
41            4.5           2.3            1.3           0.3  Iris-setosa
42            4.4           3.2            1.3           0.2  Iris-setosa
43            5.0           3.5            1.6           0.6  Iris-setosa
44            5.1           3.8            1.9           0.4  Iris-setosa
45            4.8           3.0            1.4           0.3  Iris-setosa
46            5.1           3.8            1.6           0.2  Iris-setosa
47            4.6           3.2            1.4           0.2  Iris-setosa
48            5.3           3.7            1.5           0.2  Iris-setosa
49            5.0           3.3            1.4           0.2  Iris-setosa

In [ ]:
import os
os.makedirs('191402032')

with open('191402032/file.txt', 'w+') as c:
    c.write('pesan kalian untuk lab kedepannya')
    c.write('\nmaaf bang tolong tugasnya jangan banyak banget rasanya seperti lagi ngerjain ujian')
    
with open('191402032/file.txt', 'r') as c:
    print(c.read())

pesan kalian untuk lab kedepannya
maaf bang tolong tugasnya jangan banyak banget rasanya seperti lagi ngerjain ujian